### ISSUE TITLE
Fail when installing requirements

### ISSUE THREAD

**Issue by LumenYoung** [foges/whisper-dictation#5]
```
Collecting pyobjc-framework-Cocoa
  Using cached pyobjc-framework-Cocoa-9.0.1.tar.gz (5.6 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-j6qzim_5/pyobjc-framework-cocoa_c82e1c161da040b8a08968c30245a776/setup.py", line 22, in <module>
          Extension(
        File "/tmp/pip-install-j6qzim_5/pyobjc-framework-cocoa_c82e1c161da040b8a08968c30245a776/pyobjc_setup.py", line 462, in Extension
          os_level = get_os_level()
        File "/tmp/pip-install-j6qzim_5/pyobjc-framework-cocoa_c82e1c161da040b8a08968c30245a776/pyobjc_setup.py", line 231, in get_os_level
          subprocess.check_output(["/usr/bin/sw_vers", "-productVersion"])
        File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "/usr/lib/python3.10/subprocess.py", line 503, in run
          with Popen(*popenargs, **kwargs) as process:
        File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/usr/lib/python3.10/subprocess.py", line 1847, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/sw_vers'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.


```

**Comment by LumenYoung** [comment]
Hello, everyone. I'm pretty interested at your work, thank you for sharing this. Would you mind give me more information about the requirement? I actually didn't see any of the packages inside your requirement.txt that collects these packages.

I'm also interested to know what development environment you are using. Are you using mac? Is there any package that is mac specific? Thank you for your time!

**Comment by LumenYoung** [comment]
Ok, I think I've found the issue. It was the package `rump` . Thank you anyway
